# Generated by Django 5.2.11 on 2026-02-08 01:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=200)),
                ('cep', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem_usuario', models.ImageField(blank=True, null=True, upload_to='usuarios/')),
                ('nome', models.CharField(blank=True, max_length=30)),
                ('CPF', models.CharField(blank=True, max_length=20, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1)),
                ('email', models.EmailField(max_length=254)),
                ('tipo_usuario', models.CharField(default='Comum', max_length=200)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_pedido', models.CharField(blank=True, max_length=12, unique=True)),
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('PAGO', 'Pago'), ('E', 'Enviado'), ('F', 'Finalizado'), ('C', 'Cancelado')], default='P', max_length=10)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('endereco_entrega', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loja.endereco')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='loja.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('subtitulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('marca', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_promocional', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estoque', models.PositiveIntegerField(default=0)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('tamanho', models.CharField(blank=True, max_length=50, null=True)),
                ('avaliacao_media', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('quantidade_avaliacoes', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('imagem_principal', models.ImageField(blank=True, null=True, upload_to='./administracao_loja/static/produtos_imagens/')),
                ('slug', models.SlugField(unique=True)),
                ('ml', models.CharField(default='0', max_length=5)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='loja.categoria')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='perfumes',
            field=models.ManyToManyField(through='loja.ItemPedido', to='loja.produto'),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='perfume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.produto'),
        ),
        migrations.CreateModel(
            name='ImagemProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='imagens/produtos/')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='loja.produto')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='loja.usuario'),
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.DateTimeField(auto_now_add=True)),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('lida', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='loja.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='endereco',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.usuario'),
        ),
    ]
