# Generated by Django 5.2.11 on 2026-02-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemproduto',
            name='imagem',
            field=models.ImageField(upload_to='./administracao_loja/static/produtos_imagens/'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='imagem_usuario',
            field=models.ImageField(blank=True, null=True, upload_to='./administracao_loja/static/imagens_usuarios/'),
        ),
    ]
