# Generated by Django 5.1.5 on 2025-11-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagem_usuario',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/'),
        ),
    ]
