# Generated by Django 5.1.5 on 2025-11-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_alter_usuario_imagem_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem_principal',
            field=models.ImageField(upload_to='./imagens/'),
        ),
    ]
