# Generated by Django 5.1.5 on 2025-11-27 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_alter_produto_imagem_principal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem_principal',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/produtos/'),
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=200)),
                ('cep', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.usuario')),
            ],
        ),
        migrations.DeleteModel(
            name='enderecos',
        ),
    ]
