# Generated by Django 5.1.5 on 2025-11-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_alter_produto_imagem_principal_endereco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagem_usuario',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/usuarios/'),
        ),
    ]
