# Generated by Django 5.2.11 on 2026-03-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_alter_usuario_auth_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'permissions': [('aplicar_desconto', 'Pode aplicar desconto em produto')]},
        ),
        migrations.AddField(
            model_name='pedido',
            name='metodo_pagamento',
            field=models.CharField(choices=[('pix', 'PIX'), ('cartao', 'Cartão'), ('boleto', 'Boleto')], default='pix', max_length=10),
        ),
    ]
