# Generated by Django 5.1.5 on 2025-11-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_alter_usuario_imagem_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagem_usuario',
            field=models.ImageField(blank=True, null=True, upload_to='./usuarios/'),
        ),
    ]
