# Generated by Django 5.1.5 on 2025-12-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0008_imagemproduto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem_principal',
            field=models.ImageField(blank=True, null=True, upload_to='loja/static/html/administrador/produtos'),
        ),
    ]
