# Generated by Django 5.1.5 on 2025-12-03 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0011_alter_produto_imagem_principal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemproduto',
            name='descricao',
        ),
    ]
