# Generated by Django 5.1.5 on 2025-12-03 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0012_remove_imagemproduto_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='imagem_principal',
        ),
    ]
