# Generated by Django 5.1.5 on 2025-12-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0013_remove_produto_imagem_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem_principal',
            field=models.ImageField(blank=True, null=True, upload_to='produtos_imagens/'),
        ),
    ]
