# Generated by Django 5.1.5 on 2025-12-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0014_produto_imagem_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='numero_pedido',
            field=models.CharField(default='000000', max_length=20, unique=True),
        ),
    ]
