# Generated by Django 5.1.5 on 2025-12-10 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0015_pedido_numero_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='endereco_entrega',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loja.endereco'),
        ),
    ]
