# Generated by Django 5.1.5 on 2025-12-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0016_pedido_endereco_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='subtitulo',
            field=models.CharField(default='', max_length=200),
        ),
    ]
