# Generated by Django 5.1.5 on 2025-12-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0017_produto_subtitulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='subtitulo',
            field=models.CharField(max_length=200),
        ),
    ]
