"""
Django settings for Site project.

Generated by 'django-admin startproject' using Django 5.2.7.
"""

from pathlib import Path
import os
import dj_database_url

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = "django-insecure-7i6eu+r0w-$et@qaqx^y+!-d4-x&r89e+_!z2_vr=xzu0uh6e@"

DEBUG = True

ALLOWED_HOSTS = ["*"]

# Application definition
INSTALLED_APPS = [
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",  

    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
     "django.contrib.humanize",
    "allauth.usersessions",

    "loja",
    "accounts",
    
]
JAZZMIN_SETTINGS = {
    "site_title": "NL Importados",
    "site_header": "NL Administração",
    "site_brand": "NL IMPORTADOS",
    "welcome_sign": "Bem-vindo ao Painel NL",
    "copyright": "NL Importados",
    
     # pode trocar tema
}
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "allauth.usersessions.middleware.UserSessionsMiddleware",
]

ROOT_URLCONF = "Site.urls"
SITE_ID = 1

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates", BASE_DIR / ""],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


WSGI_APPLICATION = "Site.wsgi.application"

# Database: SQLite em memória (somente para teste no Vercel)
DATABASE_URL="postgresql://neondb_owner:npg_hRnYHLI8Pl5K@ep-green-pine-aegf0im0-pooler.c-2.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
DATABASES = {
    'default': dj_database_url.config(
        default=DATABASE_URL,
        conn_max_age=600, # Opcional: pool de conexões
        ssl_require=True # Essencial para Neon
    )
}

# Se estiver usando PostgreSQL (Vercel + Neon)
if os.getenv("DATABASE_URL"):
    DATABASES["default"]["OPTIONS"] = {
        "sslmode": "require"
    }

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

LANGUAGE_CODE = "pt-br"
TIME_ZONE = "America/Sao_Paulo"
USE_I18N = True
USE_TZ = True
LOGIN_REDIRECT_URL = '/'  # ou use a URL que corresponde ao seu template
# settings.py

SOCIALACCOUNT_AUTO_SIGNUP = True
USERSESSIONS_ADAPTER = "app.adapters.CustomUserSessionsAdapter"


# Static files
STATIC_URL = "/static/"
STATICFILES_DIRS = [
    BASE_DIR  / "loja" / 'static',
 
]
STATIC_ROOT = BASE_DIR / "staticfiles"

USE_X_FORWARDED_HOST = True
# Media
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
ACCOUNT_EMAIL_VERIFICATION = 'none'
SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE": ["profile", "email"],
        "AUTH_PARAMS": {"access_type": "online"},
        "client_id": os.getenv("GOOGLE_CLIENT_ID"),
        "secret": os.getenv("GOOGLE_SECRET"),
    }
}
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_UNIQUE_EMAIL = True
SOCIALACCOUNT_AUTO_SIGNUP = True
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']

